# ----
# Site

title: The David J. Kabakow Foundation
url: https://davidjkabakowfoundation.org
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The David J. Kabakow Foundation was established to raise funds to support research and awareness of Haemophagocytic Lymphohistiocytosis (HLH) and to promote education in the medical community.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: The David J. Kabakow Foundation
  links:
    - https://www.facebook.com/David-J-Kabakow-Foundation-109016067907837

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" paypalExpress="false"></script><iframe allowpaymentrequest="" frameborder="0" height="900px" name="donorbox" scrolling="no" seamless="seamless" src="https://donorbox.org/embed/david-j-kabakow-foundation" style="max-width: 500px; min-width: 250px; max-height:none!important" width="100%"></iframe>'
newsletter_action: "https://davidjkabakowfoundation.us1.list-manage.com/subscribe/post?u=a667b8de92d9f51f2bdb10d7b&amp;id=9251770264"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
